export { default as Header } from './Header'
export { default as Footer } from './Footer'
export { default as Hero } from './Hero'
export { default as Advantages } from './Advantages'
export { default as Pricing } from './Pricing'
